### PR TITLE
Removing accidentally committed vendor libraries

### PR DESCRIPTION
**Pull request by pkopac**
* Go build tooling isn't capable of deduplicating dependencies right now
* I think `Godeps` was renamed to `vendor`, but author forgot to change `.gitignore`
* Amended `.gitignore`, left `Godeps` as well, just in case
* Tested locally that this was the problem I referenced in here: #1

### CODE REVIEW

**Comment by pkopac** [comment]
@appleboy: added the correct build step to travis, too, so now it builds and should be compatible.

**Comment by pkopac** [comment]
@appleboy: I don't know, therefore I don't remove it ;) It certainly doesn't hurt in the `.gitignore`, but if you want, you can remove it anytime. Is this good to go?

**Comment by appleboy** [comment]
Why need to update vendor folder?

You can try the following steps:

$ git clone https://github.com/gin-contrib/static.git
$ cd example/simple
$ govendor init
$ govendor fetch github.com/gin-contrib/static
$ govendor fetch github.com/gin-gonic/gin
$ go run example.go

It is working for me so I don't know this PR fix issue what you want?

**Comment by pkopac** [comment]
@appleboy: why do I need to update dependencies?
Because that's how it's meant to be working.
You are not supposed to be committing other people's code in your repository.

I never said it breaks your example. It breaks any program that uses this library, though. Because of the committed dependencies that are duplicate towards the standard Go dependency system and break on compilation:
`router.Use(static.Serve("/", static.LocalFile("./static", false)))`

Error: (as mentioned in #1)
`cannot use static.Serve("/", static.LocalFile("./static", false)) (type "github.com/gin-contrib/static/vendor/github.com/gin-gonic/gin".HandlerFunc) as type "github.com/gin-gonic/gin".HandlerFunc in argument to router.Use`

Do you see the `vendor` there? It's breaking it. The libraries shouldn't be fetched there. There should be only the config in the folder, nothing else.

**Comment by appleboy** [comment]
@pkopac Please remove your vendor folder first and fetch again.

Using static library project:

```
$ govendor fetch github.com/gin-contrib/static
```

I can't see the `github.com/gin-contrib/static/vendor` path in vendor folder. What is your vendor tool?

**Comment by pkopac** [comment]
@appleboy, I am not using vendoring tools. I haven't even known about them up to now :)
I'm using the original `go get ./...` in my builds. So no, I can't remove *my* vendor folder. There is none.

The problem is, you have committed the libraries inside *your* vendor folder, which makes it incompatible wiht standard `go get ./...`
See the libraries, which shouldn't be there: https://github.com/gin-contrib/static/tree/master/vendor
That's the path you can't see. That's *it*.

I removed the dependency on this library now, because I need the builds running.

**Comment by appleboy** [comment]
@pkopac I got your point. I will remove vendor folder.

**Pull request closed without merging**
